### ISSUE TITLE
[Kubernetes]: Visualization Display errors for Kubernetes Jobs and Cronjobs Dashboards

### ISSUE THREAD

**Issue by Danouchka** [elastic/integrations#11060]
### Integration Name

Kubernetes [kubernetes]

### Integration Version

1.67.0

### Agent Version

8.15.0

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.15.1

### OS Version and Architecture

Elastic Cloud GCP Belgium

### Error Message

Visualizations below not rendered properly

![Image](https://github.com/user-attachments/assets/b70a5905-18b4-4290-984e-cb5c9bfc0390)

Error: 
`The above error occurred in l:

    at l (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:450:80089)
    at S (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:365:754987)
    at div
    at div
    at t.default (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:376:230815)
    at R (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:397:20810)
    at div
    at https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:360:46261
    at div
    at https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:360:46261
    at x (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/plugin/expressionMetricVis/1.0.0/expressionMetricVis.chunk.1.js:1:1408)
    at div
    at https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:360:46261
    at x (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-src/kbn-ui-shared-deps-src.js:43:313212)
    at L (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-src/kbn-ui-shared-deps-src.js:43:314013)
    at p (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-src/kbn-ui-shared-deps-src.js:43:308941)
    at c (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:365:190149)
    at t (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-src/kbn-ui-shared-deps-src.js:43:223282)
    at ee (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-src/kbn-ui-shared-deps-src.js:43:223788)
    at Context (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/core/core.entry.js:16:207034)
    at p (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:365:594284)
    at d (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:365:150723)
    at v (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:360:46705)
    at a (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:388:11593)
    at f (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:6:59856)
    at x (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:365:620368)
    at s (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:376:203784)
    at a (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:365:965943)
    at m (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:381:1072272)
    at T (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/plugin/expressionMetricVis/1.0.0/expressionMetricVis.plugin.js:1:11438)
    at D (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/plugin/expressionMetricVis/1.0.0/expressionMetricVis.plugin.js:1:11763)
    at C (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io:9243/f66ec5b0ddd9/bundles/plugin/expressionMetricVis/1.0.0/expressionMetricVis.plugin.js:1:12243)`

### What did you do?

Nothing 

### What did you see?

![Image](https://github.com/user-attachments/assets/b70a5905-18b4-4290-984e-cb5c9bfc0390)

### What did you expect to see?

Properly rendered visualization

**Comment by Danouchka** [comment]
cc @mlunadia

**Comment by gizas** [comment]
Assigned @constanca-m  that currently is on sdh support.

From first look seems a visualisation problem. This visualisation is based on kubernetes.job.pods.* metics.
Can you please provide us the discovery info for those metrics?
Have you waited a little until agent sent some data and then refreshed the page?

Additionally:
- We would like to see the status of elastic-agent installed
- Some logs from elastic-agent to see if any problems occured? Probably a diagnostics would be ideal?
- `kubectl get jobs -A` from your k8s cluster

**Comment by Danouchka** [comment]
Hi 

my agents are running for a while  and are healthy 

I have no jobs but the visualizations would render well in previous intégrations versions. 

It's not because I have 0 results that i should get these visualization errors.  

Thank you

**Comment by Danouchka** [comment]
Hi 

I also cleaned my browser cache but it's the same 

Best, Dan

**Comment by gizas** [comment]
I  was able to reproduce it with 1.67.0 

See 1.66.4:
![Image](https://github.com/user-attachments/assets/9f8117d3-e735-4f95-9c0d-3660802d7b1b)

See 1.67.0:
![Image](https://github.com/user-attachments/assets/247203c4-67a5-49d9-9727-73c39c61691b)

Seems that during export of last version something broke. We will investigate

**Comment by gizas** [comment]
I did some investigation and seems that just the rendering of the visualisations just changed from 8.14 to 8.15 

See below 8.14.0
![Image](https://github.com/user-attachments/assets/fb98f707-ce3c-4941-ade8-b892aec7e2a8)

In my case even in 8.15.1 when I had the above red error pages, when data came in, the visualisation worked. 

![Image](https://github.com/user-attachments/assets/3f28e4a3-7226-49d9-b2ce-1f3cb4745e12)


@Danouchka can I request once more the following:

```bash
kubectl get jobs -A
watch "kubectl get jobs -A"
kubectl get pods -A | grep -i elastic
```

**Comment by gizas** [comment]
FYI I added this issue here for kibana team: https://github.com/elastic/kibana/issues/192569

**Comment by Danouchka** [comment]
I het the following:

```
#watch "kubectl get jobs -A"
Every 2.0s: kubectl get jobs -A                                                                                                                                                                                                                                   

No resources found

#cloudshell:~ (elastic-sa)$ kubectl get pods -A | grep -i elastic
kube-system   elastic-agent-jzmhl                                     1/1     Running   0               2d19h
kube-system   elastic-agent-ldkl7                                     1/1     Running   0               2d19h
kube-system   elastic-agent-lmxf5                                     1/1     Running   0               2d19h
```

**Comment by m-a-leclercq** [comment]
Having the same issue with EDOT.

**Comment by Danouchka** [comment]
Hello, is this the same kind of error than https://github.com/user-attachments/assets/97dba9ca-8ed3-4be6-9ecc-bc953496e8a7

>    at c (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/plugin/discover/1.0.0/discover.chunk.0.js:1:75702)
    at div
    at https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:365:345682
    at https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:365:334698
    at f (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:365:944119)
    at div
    at https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:365:345549
    at t (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:365:336195)
    at https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:388:401703
    at https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:388:133270
    at div
    at https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:388:133739
    at div
    at t (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:365:98156)
    at https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:388:134129
    at d (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:594:61876)
    at div
    at div
    at div
    at https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:365:912739
    at https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:376:15486
    at https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:388:32672
    at t (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:365:21757)
    at x (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:365:21675)
    at https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:381:979049
    at div
    at span
    at W (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/plugin/discover/1.0.0/discover.chunk.0.js:1:46759)
    at s
    at div
    at https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:360:46261
    at b (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:298:8652)
    at div
    at https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:360:46261
    at O (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:355:64214)
    at https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:360:46261
    at B (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/plugin/discover/1.0.0/discover.chunk.11.js:1:3623)
    at G (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/plugin/discover/1.0.0/discover.chunk.11.js:1:4457)
    at se (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/plugin/discover/1.0.0/discover.chunk.11.js:1:9583)
    at l (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/plugin/discover/1.0.0/discover.chunk.0.js:1:18921)
    at Provider (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/plugin/kibanaReact/1.0.0/kibanaReact.plugin.js:1:25355)
    at x (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-src/kbn-ui-shared-deps-src.js:43:313212)
    at L (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-src/kbn-ui-shared-deps-src.js:43:314013)
    at p (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-src/kbn-ui-shared-deps-src.js:43:308941)
    at c (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:365:190149)
    at t (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-src/kbn-ui-shared-deps-src.js:43:223282)
    at ee (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-src/kbn-ui-shared-deps-src.js:43:223788)
    at Context (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/core/core.entry.js:16:207034)
    at p (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:365:594284)
    at d (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:365:150723)
    at v (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:360:46705)
    at a (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:388:11593)
    at f (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:6:59856)
    at x (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:365:620368)
    at s (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:376:203784)
    at a (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:365:965943)
    at m (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:381:1072272)
    at w (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/plugin/discover/1.0.0/discover.chunk.0.js:1:22193)
    at x (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/plugin/discover/1.0.0/discover.chunk.0.js:1:22518)
    at D (https://sa-da-ec-gcp-clus-02.kb.europe-west1.gcp.cloud.es.io/f66ec5b0ddd9/bundles/plugin/discover/1.0.0/discover.chunk.0.js:1:22998)

**Comment by markov00** [comment]
The error should be fixed in 8.16 https://github.com/elastic/kibana/pull/190966
