### ISSUE TITLE
mage importBeats error: panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by aspacca** [elastic/integrations#1301]
I've followed the instruction at https://github.com/elastic/integrations/blob/master/docs/import_from_beats.md

Not sure if the error is related to current failing build status
```
$ mage -v ImportBeats
[...]
021/07/08 10:07:09 	No docs found (path: ../beats/x-pack/filebeat/module/googlecloud/_meta/docs.asciidoc), skipped
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.policyTemplateContent.toMetadataPolicyTemplates(0xc0004a1580, 0xb, 0x149bc4b, 0x4, 0xc00191a3f0, 0xc0004a1580, 0xb, 0x149bc4b)
	/Users/andreaspacca/Sources/integrations/dev/import-beats/policy_templates.go:45 +0xed0
main.(*packageRepository).createPackagesFromSource(0xc00177bcf8, 0x149cf0b, 0x8, 0x149fdad, 0xf, 0x149bdb7, 0x4, 0x0, 0x0)
	/Users/andreaspacca/Sources/integrations/dev/import-beats/packages.go:228 +0xd45
main.build(0x149cf0b, 0x8, 0x14a2857, 0x15, 0x149cc60, 0x7, 0x149d223, 0x8, 0x149d4f1, 0x9, ...)
	/Users/andreaspacca/Sources/integrations/dev/import-beats/main.go:128 +0x31c
main.main()
	/Users/andreaspacca/Sources/integrations/dev/import-beats/main.go:102 +0x605
exit status 2
```

**Comment by aspacca** [comment]
I can see that googlecloude module has no fileset folder

```
$ ls -lah ../beats/x-pack/filebeat/module/googlecloud/
total 8
drwxr-xr-x   4 andreaspacca  staff   128B Jun  4 10:31 .
drwxr-xr-x  53 andreaspacca  staff   1.7K Jul  6 16:40 ..
drwxr-xr-x   3 andreaspacca  staff    96B Jun  4 10:31 _meta
-rw-r--r--   1 andreaspacca  staff    13B Jun  4 10:31 module.yml
```

**Comment by aspacca** [comment]
After adding a dummy fileset directory and a `ingest` one I'm able to continue through the process till another error
```
2021/07/08 10:31:04 creating from logs source failed: reading image size failed: opening image failed (path: ../kibana/src/plugins/home/public/assets/logos/o365.svg): parsing width failed (value: 236px): parsing width failed (value: 236px): strconv.ParseFloat: parsing "236px": invalid syntax
```

**Comment by mtojek** [comment]
Let me know if you need some assist with the script. We used it for the initial migration of modules one year ago. Definitely it isn't ideal, but helps with most of migration tasks. Frankly speaking it should be deprecated (and removed) few months ago, but the migration is not finished yet.

**Comment by aspacca** [comment]
No problem, I didn't know it was deprecated and to be removed.
I found in the instruction to open an issue if it did't work. I will close then.

**Comment by mtojek** [comment]
No no, it isn't deprecated yet (just should be if we manage to migrate all modules). Let's keep it open :)
