### ISSUE TITLE
[crowdstrike] 'Is FDR queue' option not being honored

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#2646]
The config is checking for `fdr_queue`, but the manifest names the variable `is_fdr_queue`. This means that the config for parsing the SQS message format from CrowdStrike is not loaded into the Agent policy.

https://github.com/elastic/integrations/blob/a7efde55178c97f90b61307609a37ca944bba4c1/packages/crowdstrike/data_stream/fdr/manifest.yml#L34

https://github.com/elastic/integrations/blob/a7efde55178c97f90b61307609a37ca944bba4c1/packages/crowdstrike/data_stream/fdr/agent/stream/aws-s3.yml.hbs#L35

**Comment by andrewkroh** [comment]
I fixed the issue with the `{{#if is_fdr_queue}}`, but this opened the path to an untested part of the handlebar template. It is yielding this error from Kibana.

```
YAMLException: end of the stream or a document separator is expected at line 20, column 1:
    }
    ^
    at generateError (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at readDocument (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:1545:5)
    at loadDocuments (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:1588:5)
    at load (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:1614:19)
    at safeLoad (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:1637:10)
    at compileTemplate (/usr/share/kibana/x-pack/plugins/fleet/server/services/epm/agent/agent.js:33:57)
    at _compilePackageStream (/usr/share/kibana/x-pack/plugins/fleet/server/services/package_policy.js:781:43)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at _compilePackageStreams (/usr/share/kibana/x-pack/plugins/fleet/server/services/package_policy.js:710:10)
    at /usr/share/kibana/x-pack/plugins/fleet/server/services/package_policy.js:605:31
    at async Promise.all (index 1)
    at PackagePolicyService.create (/usr/share/kibana/x-pack/plugins/fleet/server/services/package_policy.js:160:16)
    at createPackagePolicyHandler (/usr/share/kibana/x-pack/plugins/fleet/server/routes/package_policy/handlers.js:105:27) {
  reason: 'end of the stream or a document separator is expected',
  mark: Mark {
    name: null,
    buffer: 'queue_url: https://web.hook.sh/18b7da4a-9238-4ed0-bc17-6970c935737b \n' +
      'endpoint: amazonaws.com\n' +
      'access_key_id: AABB\n' +
      'secret_access_key: abcdebf\n' +
      'sqs.notification_parse_script: function parse(n) {\n' +
      '  var m = JSON.parse(n);\n' +
      '  var evts = [];\n' +
      '  var files = m.files;\n' +
      '  var bucket = m.bucket;\n' +
      '  if (!Array.isArray(files) || (files.length == 0) || bucket == null || bucket == "") {\n' +
      '    return evts;\n' +
      '  }\n' +
      '  files.forEach(function(f){\n' +
      '    var evt = new S3EventV2();\n' +
      '    evt.SetS3BucketName(bucket);\n' +
      '    evt.SetS3ObjectKey(f.path);\n' +
      '    evts.push(evt);\n' +
      '  });\n' +
      '  return evts;\n' +
      '}\n' +
      '\n' +
      'tags:\n' +
      '  - forwarded\n' +
      '  - crowdstrike-fdr\n' +
      'publisher_pipeline.disable_host: true\n' +
      '\x00',
    position: 556,
    line: 19,
    column: 0
  }
}
```

**Comment by andrewkroh** [comment]
https://github.com/elastic/integrations/pull/2701 fixes the multi-line script issues.
