### ISSUE TITLE
[Prometheus integration] leader election enabled for non k8s environment causing metricbeat crash 

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/integrations#3905]
Leader election setting is enabled by default, on k8s environment it is a correct configuration and does not cause any issue.
But in case running prometheus not in k8s (for example in docker container), next error occurs:

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/28299531/181793886-d92c5bcb-862f-42a8-9cc6-ebcac24d4ae8.png">

How to reproduce:
`elastic-package stack up -d -v`
run prometheus in docker - https://prometheus.io/docs/prometheus/latest/installation/
enable prometheus integration

**Comment by tetianakravchenko** [comment]
mentioned errors:
```
{"log.level":"error","@timestamp":"2022-08-18T09:02:02.484Z","log.origin":{"file.name":"process/stdlogger.go","file.line":54},"message":"metricbeat_monitoring stderr: \"panic: close of closed channel\\n\\ngoroutine 2015 [running]:\\ngithub.com/elastic/beats/v7/metricbeat/beater.(*Metricbeat).Stop(0xc0009d44d0)\\n\\t/go/src/github.com/elastic/beats/metricbeat/beater/metricbeat.go:276 +0x28\\ngithub.com/elastic/beats/v7/libbeat/cmd/instance.(*Beat).launch.func5()\\n\\t/go/src/github.com/elastic/beats/libbeat/cmd/instance/beat.go:461 +0x68\\nsync.(*Once).doSlow(\"","agent.console.name":"metricbeat_monitoring","agent.console.type":"stderr","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-08-18T09:02:02.484Z","log.origin":{"file.name":"process/stdlogger.go","file.line":54},"message":"metricbeat_monitoring stderr: \"0xc0010807d0, 0xc001201c00)\\n\\t/usr/local/go/src/sync/once.go:68 +0x138\\nsync.(*Once).Do(0xc0010807d0, 0xc001201c00)\\n\\t/usr/local/go/src/sync/once.go:59 +0x45\\ngithub.com/elastic/elastic-agent-libs/service.HandleSignals.func1()\\n\\t/go/pkg/mod/github.com/elastic/elastic-agent-libs@v0.2.5/service/service.go:60 +0x20c\\ncreated by github.com/elastic/elastic-agent-libs/service.HandleSignals\\n\\t/go/pkg/mod/github.com/elastic/elastic-agent-libs@v0.2.5/service/service.go:49 +0x25c\\n\"","agent.console.name":"metricbeat_monitoring","agent.console.type":"stderr","ecs.version":"1.6.0"}
```
is coming because of `Bearer Token File` default value defined - on not k8s environment it shouldn't be defined.

Even when  `Bearer Token File` is not defined prometheus metrics do not appear, only after disabling leader election - all works.
