### ISSUE TITLE
Nginx Ingress Controller: "error" data stream

### ISSUE THREAD

**Issue by mtojek** [elastic/integrations#467]
# Package / Dataset creation or update checklist

This checklist is intended for Devs which create or update a package to make sure they are consistent.

Follow-up on the issue: https://github.com/elastic/integrations/issues/373 (missed during the migration assessment).

## All Changes

* [ ] Change follows [development guidelines](https://github.com/elastic/integrations/tree/master/doc/development/guidelines)
* [ ] Supported versions of the subject being monitored are documented
* [ ] Supported operating systems are documented (if applicable)
* [ ] [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
* [ ] Documentation
* [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [ ] At least a manual test with ES / Kibana / Agent has been performed.
* [ ] The required Kibana version is set to the lowest version used in the manual test.

### Dashboards

* [ ] Dashboards exists (if applicable)
* [ ] Screenshots of added / updated dashboards
* [ ] Datastream filters added to visualizations

## Log datasets

* [ ] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
* [ ] Generated output for at least 1 log file exists

## Metric datasets

This entry is currently _recommended_. It will be mandatory once we provide better support for it.

* [ ] Sample event (`sample_event.json`) exists

**Comment by mtojek** [comment]
I managed to run the Nginx ingress controller as Docker container without the Kubernetes master. The application is failing for ca. 90 seconds printing error logs, which is actually the desired effect in terms of ingestion and pipeline/system tests :)

Dockerfile:

```
FROM us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.40.2

ENV KUBERNETES_SERVICE_HOST=127.0.0.1
ENV KUBERNETES_SERVICE_PORT=443

# User is required to create /var/run/secrets directories
USER root
RUN mkdir -p /var/run/secrets/kubernetes.io/serviceaccount

# Pass the check on non-empty account token
RUN echo token > /var/run/secrets/kubernetes.io/serviceaccount/token

# Create directory to expose service logs
RUN mkdir -p /tmp/service_logs/

CMD ["sh", "-c", "/nginx-ingress-controller --log_file=/tmp/service_logs/error.log -v=10 2>&1 | tee /tmp/service_logs/error.log"]
```

Error logs:

```
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:       v0.40.2
  Build:         fc4ccc5eb0e41be2436a978b01477fc354f31643
  Repository:    https://github.com/kubernetes/ingress-nginx
  nginx version: nginx/1.19.3

-------------------------------------------------------------------------------

W1215 14:15:13.815929       8 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
E1215 14:15:13.816036       8 config.go:489] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
I1215 14:15:13.816067       8 main.go:236] "Creating API client" host="https://127.0.0.1:443"
I1215 14:15:13.816334       8 main.go:256] "Trying to discover Kubernetes version"
I1215 14:15:13.816598       8 round_trippers.go:423] curl -k -v -XGET  -H "Authorization: Bearer token" -H "Accept: application/json, */*" -H "User-Agent: nginx-ingress-controller/v0.40.2 (linux/amd64) ingress-nginx/fc4ccc5eb0e41be2436a978b01477fc354f31643" 'https://127.0.0.1:443/version?timeout=32s'
I1215 14:15:13.816837       8 round_trippers.go:443] GET https://127.0.0.1:443/version?timeout=32s  in 0 milliseconds
I1215 14:15:13.816854       8 round_trippers.go:449] Response Headers:
E1215 14:15:13.816901       8 main.go:265] "Unexpected error discovering Kubernetes version" err="Get \"https://127.0.0.1:443/version?timeout=32s\": dial tcp 127.0.0.1:443: connect: connection refused" attempt=0
I1215 14:15:14.859153       8 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: nginx-ingress-controller/v0.40.2 (linux/amd64) ingress-nginx/fc4ccc5eb0e41be2436a978b01477fc354f31643" -H "Authorization: Bearer token" 'https://127.0.0.1:443/version?timeout=32s'
I1215 14:15:14.860115       8 round_trippers.go:443] GET https://127.0.0.1:443/version?timeout=32s  in 0 milliseconds
I1215 14:15:14.860160       8 round_trippers.go:449] Response Headers:
E1215 14:15:14.860435       8 main.go:265] "Unexpected error discovering Kubernetes version" err="Get \"https://127.0.0.1:443/version?timeout=32s\": dial tcp 127.0.0.1:443: connect: connection refused" attempt=1
I1215 14:15:16.393422       8 round_trippers.go:423] curl -k -v -XGET  -H "User-Agent: nginx-ingress-controller/v0.40.2 (linux/amd64) ingress-nginx/fc4ccc5eb0e41be2436a978b01477fc354f31643" -H "Accept: application/json, */*" -H "Authorization: Bearer token" 'https://127.0.0.1:443/version?timeout=32s'
I1215 14:15:16.395020       8 round_trippers.go:443] GET https://127.0.0.1:443/version?timeout=32s  in 1 milliseconds
I1215 14:15:16.395066       8 round_trippers.go:449] Response Headers:
E1215 14:15:16.395159       8 main.go:265] "Unexpected error discovering Kubernetes version" err="Get \"https://127.0.0.1:443/version?timeout=32s\": dial tcp 127.0.0.1:443: connect: connection refused" attempt=2
I1215 14:15:18.854802       8 round_trippers.go:423] curl -k -v -XGET  -H "User-Agent: nginx-ingress-controller/v0.40.2 (linux/amd64) ingress-nginx/fc4ccc5eb0e41be2436a978b01477fc354f31643" -H "Authorization: Bearer token" -H "Accept: application/json, */*" 'https://127.0.0.1:443/version?timeout=32s'
I1215 14:15:18.855413       8 round_trippers.go:443] GET https://127.0.0.1:443/version?timeout=32s  in 0 milliseconds
I1215 14:15:18.855468       8 round_trippers.go:449] Response Headers:
E1215 14:15:18.855777       8 main.go:265] "Unexpected error discovering Kubernetes version" err="Get \"https://127.0.0.1:443/version?timeout=32s\": dial tcp 127.0.0.1:443: connect: connection refused" attempt=3
I1215 14:15:22.553256       8 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: nginx-ingress-controller/v0.40.2 (linux/amd64) ingress-nginx/fc4ccc5eb0e41be2436a978b01477fc354f31643" -H "Authorization: Bearer token" 'https://127.0.0.1:443/version?timeout=32s'
I1215 14:15:22.554146       8 round_trippers.go:443] GET https://127.0.0.1:443/version?timeout=32s  in 0 milliseconds
I1215 14:15:22.554178       8 round_trippers.go:449] Response Headers:
E1215 14:15:22.554606       8 main.go:265] "Unexpected error discovering Kubernetes version" err="Get \"https://127.0.0.1:443/version?timeout=32s\": dial tcp 127.0.0.1:443: connect: connection refused" attempt=4
I1215 14:15:27.936417       8 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: nginx-ingress-controller/v0.40.2 (linux/amd64) ingress-nginx/fc4ccc5eb0e41be2436a978b01477fc354f31643" -H "Authorization: Bearer token" 'https://127.0.0.1:443/version?timeout=32s'
I1215 14:15:27.937630       8 round_trippers.go:443] GET https://127.0.0.1:443/version?timeout=32s  in 0 milliseconds
I1215 14:15:27.937899       8 round_trippers.go:449] Response Headers:
E1215 14:15:27.938010       8 main.go:265] "Unexpected error discovering Kubernetes version" err="Get \"https://127.0.0.1:443/version?timeout=32s\": dial tcp 127.0.0.1:443: connect: connection refused" attempt=5
I1215 14:15:35.815744       8 round_trippers.go:423] curl -k -v -XGET  -H "User-Agent: nginx-ingress-controller/v0.40.2 (linux/amd64) ingress-nginx/fc4ccc5eb0e41be2436a978b01477fc354f31643" -H "Accept: application/json, */*" -H "Authorization: Bearer token" 'https://127.0.0.1:443/version?timeout=32s'
I1215 14:15:35.816482       8 round_trippers.go:443] GET https://127.0.0.1:443/version?timeout=32s  in 0 milliseconds
I1215 14:15:35.816531       8 round_trippers.go:449] Response Headers:
E1215 14:15:35.816625       8 main.go:265] "Unexpected error discovering Kubernetes version" err="Get \"https://127.0.0.1:443/version?timeout=32s\": dial tcp 127.0.0.1:443: connect: connection refused" attempt=6
I1215 14:15:47.924715       8 round_trippers.go:423] curl -k -v -XGET  -H "Authorization: Bearer token" -H "Accept: application/json, */*" -H "User-Agent: nginx-ingress-controller/v0.40.2 (linux/amd64) ingress-nginx/fc4ccc5eb0e41be2436a978b01477fc354f31643" 'https://127.0.0.1:443/version?timeout=32s'
I1215 14:15:47.925385       8 round_trippers.go:443] GET https://127.0.0.1:443/version?timeout=32s  in 0 milliseconds
I1215 14:15:47.925418       8 round_trippers.go:449] Response Headers:
E1215 14:15:47.925673       8 main.go:265] "Unexpected error discovering Kubernetes version" err="Get \"https://127.0.0.1:443/version?timeout=32s\": dial tcp 127.0.0.1:443: connect: connection refused" attempt=7
I1215 14:16:06.102271       8 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: nginx-ingress-controller/v0.40.2 (linux/amd64) ingress-nginx/fc4ccc5eb0e41be2436a978b01477fc354f31643" -H "Authorization: Bearer token" 'https://127.0.0.1:443/version?timeout=32s'
I1215 14:16:06.102835       8 round_trippers.go:443] GET https://127.0.0.1:443/version?timeout=32s  in 0 milliseconds
I1215 14:16:06.102860       8 round_trippers.go:449] Response Headers:
E1215 14:16:06.102916       8 main.go:265] "Unexpected error discovering Kubernetes version" err="Get \"https://127.0.0.1:443/version?timeout=32s\": dial tcp 127.0.0.1:443: connect: connection refused" attempt=8
I1215 14:16:33.325558       8 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: nginx-ingress-controller/v0.40.2 (linux/amd64) ingress-nginx/fc4ccc5eb0e41be2436a978b01477fc354f31643" -H "Authorization: Bearer token" 'https://127.0.0.1:443/version?timeout=32s'
I1215 14:16:33.326405       8 round_trippers.go:443] GET https://127.0.0.1:443/version?timeout=32s  in 0 milliseconds
I1215 14:16:33.326437       8 round_trippers.go:449] Response Headers:
E1215 14:16:33.326554       8 main.go:265] "Unexpected error discovering Kubernetes version" err="Get \"https://127.0.0.1:443/version?timeout=32s\": dial tcp 127.0.0.1:443: connect: connection refused" attempt=9
F1215 14:16:33.326604       8 main.go:294] Error while initiating a connection to the Kubernetes API server. This could mean the cluster is misconfigured (e.g. it has invalid API server certificates or Service Accounts configuration). Reason: Get "https://127.0.0.1:443/version?timeout=32s": dial tcp 127.0.0.1:443: connect: connection refused
Refer to the troubleshooting guide for more information: https://kubernetes.github.io/ingress-nginx/troubleshooting/
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc00000e001, 0xc0004fc6c0, 0x1cd, 0x228)
	k8s.io/klog/v2@v2.3.0/klog.go:996 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x28fb700, 0xc000000003, 0x0, 0x0, 0xc000344770, 0x28499eb, 0x7, 0x126, 0x0)
	k8s.io/klog/v2@v2.3.0/klog.go:945 +0x191
k8s.io/klog/v2.(*loggingT).printf(0x28fb700, 0x3, 0x0, 0x0, 0x1c19509, 0x13f, 0xc00009ff08, 0x1, 0x1)
	k8s.io/klog/v2@v2.3.0/klog.go:733 +0x17a
k8s.io/klog/v2.Fatalf(...)
	k8s.io/klog/v2@v2.3.0/klog.go:1463
main.handleFatalInitError(...)
	k8s.io/ingress-nginx/cmd/nginx/main.go:294
main.main()
	k8s.io/ingress-nginx/cmd/nginx/main.go:78 +0x32f

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x28fb700)
	k8s.io/klog/v2@v2.3.0/klog.go:1131 +0x8b
created by k8s.io/klog/v2.init.0
	k8s.io/klog/v2@v2.3.0/klog.go:416 +0xd8
```

/cc @ChrsMark

**Comment by ChrsMark** [comment]
Nice @mtojek ! These logs we would like to collect! Even if they are not always "errors" and some of them can be warnings or info logs I think that we want all of them. Wondering if we can call the datastream `error` since it can be misleading 🤔 ?

**Comment by mtojek** [comment]
> Wondering if we can call the datastream error since it can be misleading 🤔 ?

I put all these entries into the `error` bucket as they're logged to stderr.

If you have any other suggestion, I'm happy to rename it. Maybe `log`? `application`?

**Comment by ChrsMark** [comment]
Checked what we do in `nginx` and `apache` and it seems we use `error` to collect same kind of application logs so I guess we can follow the same here :).
