### ISSUE TITLE
Checking AWS integration install failures on 8.5

### ISSUE THREAD

**Issue by zmoog** [elastic/integrations#4895]
Investigating a user-reported failure of the AWS integration on 8.5.

The error is the following:

```text
Failure to install package [aws]: [Error: Saved object [dashboard/aws-131a1550-5a0b-11ed-a807-bd2da8f2e79b] not found]
```

**Comment by zmoog** [comment]
Here are the exact versions I am using in this first test:

Stack: 8..5.3
AWS integration: 1.28.3

**Comment by zmoog** [comment]
The first attempt succeeded:

https://user-images.githubusercontent.com/25941/209300807-b92cf692-af70-4ad5-8797-de6d3296037e.mp4

**Comment by zmoog** [comment]
The simple case is okay. 

Now I want to test if the user is facing the following issue: https://github.com/elastic/kibana/issues/147364

**Comment by zmoog** [comment]
I was able to reproduce what it looks like the same issue the user is facing by following the steps described at https://github.com/elastic/kibana/issues/147364.

Here are the updated steps to reproduce the issue version using the AWS integration:

- Add AWS integration in the default space
- Create an agent policy with the AWS integration and assign it to an agent
- Wait for EC2 metrics to be ingested
- Create an Admin space
- Unassign the agent policy from the agent
- Remove the agent policy, and uninstall the AWS integration from Default space
- Switch to Admin space and add AWS integration again
- The error of saved object not found is coming

Here's the outcome:

![CleanShot 2022-12-23 at 10 18 24@2x](https://user-images.githubusercontent.com/25941/209308867-406b929e-3dd9-45b1-92d0-abf4c38e8b7d.png)

**Comment by zmoog** [comment]
I tried to adapt to AWS and apply the workaround suggested at https://github.com/elastic/kibana/issues/147364 with no luck:



```shell

export ES_USER="username"
export ES_PASS="password"
export ES_HOST="localhost"
export ES_PORT="9200"

# Create the security role "fleet_superuser"
curl -sk -XPOST --user $ES_USER:$ES_PASS -H 'content-type:application/json' https://$ES_HOST:$ES_PORT/_security/role/fleet_superuser -d '
{
    "indices": [
        {
            "names": [".fleet*", ".kibana*"],
            "privileges": ["all"],
            "allow_restricted_indices": true
        }
    ]
}'

# Output: {"role":{"created":true}}


# Create the user "fleet_superuser" and assign the "fleet_superuser" role to it
curl -sk -XPOST --user $ES_USER:$ES_PASS -H 'content-type:application/json' \
    https://$ES_HOST:$ES_PORT/_security/user/fleet_superuser -d '
        {
            "password": "password",
            "roles": ["superuser", "fleet_superuser"]
        }'

# Output: {"created":true}



curl -sk -XGET --user fleet_superuser:password -H 'content-type:application/json' \
    -H'x-elastic-product-origin:fleet' \
   https://$ES_HOST:$ES_PORT/.kibana/_search?size=10000 -d '
         {
   "query": {
     "bool": {
         "filter": [ 
        { "terms":  { "type": ["dashboard", "visualization", "map", "lens", "search"] }}],
       "must": [
         {"simple_query_string": {
           "query": "\"aws-*\""
         }}
       ]
     }
   }
 }
'

# Delete
curl -sk -XPOST --user fleet_superuser:password -H 'content-type:application/json' \
    -H'x-elastic-product-origin:fleet' \
   https://$ES_HOST:$ES_PORT/.kibana/_delete_by_query -d '
         {
   "query": {
     "bool": {
         "filter": [ 
        { "terms":  { "type": ["dashboard", "visualization", "map", "lens", "search"] }}],
       "must": [
         {"simple_query_string": {
           "query": "\"aws-*\""
         }}
       ]
     }
   }
 }'

# Output: {"took":164,"timed_out":false,"total":103,"deleted":103,"batches":1,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":-1.0,"throttled_until_millis":0,"failures":[]}%   

```

**Comment by zmoog** [comment]
Even after deleting all the object matching this query, I still get this error:

```text
[2022-12-23T09:59:00.440+00:00][WARN ][plugins.fleet] Failure to install package [aws]: [Error: Saved object [dashboard/aws-07d67a60-d872-11eb-8220-c9141cc1b15c] not found]
[2022-12-23T09:59:00.442+00:00][ERROR][plugins.fleet] uninstalling aws-1.28.3 after error installing: [Error: Saved object [dashboard/aws-07d67a60-d872-11eb-8220-c9141cc1b15c] not found]
[2022-12-23T09:59:00.511+00:00][ERROR][plugins.fleet] FleetError: error deleting pipeline metrics-aws.billing-1.28.3: ResponseError: illegal_argument_exception: [illegal_argument_exception] Reason: pipeline [metrics-aws.billing-1.28.3] cannot be deleted because it is the default pipeline for 1 index(es) including [.ds-metrics-aws.billing-default-2022.12.23-000001]
    at deletePipeline (/usr/share/kibana/x-pack/plugins/fleet/server/services/epm/elasticsearch/ingest_pipeline/remove.js:65:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at deleteAssets (/usr/share/kibana/x-pack/plugins/fleet/server/services/epm/packages/remove.js:175:5)
    at removeInstallation (/usr/share/kibana/x-pack/plugins/fleet/server/services/epm/packages/remove.js:67:3)
    at handleInstallPackageFailure (/usr/share/kibana/x-pack/plugins/fleet/server/services/epm/packages/install.js:203:7)
    at /usr/share/kibana/x-pack/plugins/fleet/server/services/epm/packages/install.js:389:7
    at installPackageFromRegistry (/usr/share/kibana/x-pack/plugins/fleet/server/services/epm/packages/install.js:358:12)
    at installPackage (/usr/share/kibana/x-pack/plugins/fleet/server/services/epm/packages/install.js:577:22)
    at installPackageFromRegistryHandler (/usr/share/kibana/x-pack/plugins/fleet/server/routes/epm/handlers.js:302:15)
    at Router.handle (/usr/share/kibana/node_modules/@kbn/core-http-router-server-internal/target_node/src/router.js:163:30)
    at handler (/usr/share/kibana/node_modules/@kbn/core-http-router-server-internal/target_node/src/router.js:124:50)
    at exports.Manager.execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/toolkit.js:60:28)
    at Object.internals.handler (/usr/share/kibana/node_modules/@hapi/hapi/lib/handler.js:46:20)
    at exports.execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/handler.js:31:20)
    at Request._lifecycle (/usr/share/kibana/node_modules/@hapi/hapi/lib/request.js:371:32)
    at Request._execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/request.js:281:9)
[2022-12-23T09:59:01.562+00:00][ERROR][plugins.fleet] failed to uninstall or rollback package after installation error Error: Saved object [epm-packages/aws] not found
[2022-12-23T09:59:01.562+00:00][ERROR][plugins.fleet] Error: Saved object [dashboard/aws-07d67a60-d872-11eb-8220-c9141cc1b15c] not found
    at AssignmentService.updateTagAssignments (/usr/share/kibana/x-pack/plugins/saved_objects_tagging/server/services/assignments/assignment_service.js:126:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at tagKibanaAssets (/usr/share/kibana/x-pack/plugins/fleet/server/services/epm/kibana/assets/tag_assets.js:40:3)
    at installKibanaAssetsAndReferences (/usr/share/kibana/x-pack/plugins/fleet/server/services/epm/kibana/assets/install.js:161:3)
```

**Comment by zmoog** [comment]
I may have found a potential workaround taking this issue from a slightly different perspective.

Versions:
- stack: 8.5.3
- AWS integration: 1.28.3

**Steps to create the issue**

- Create a new space called "Admin" and switch to it
- Install the AWS integration
- Enable EC2 metrics and collect some data
- Uninstall the AWS integration
- Delete the space named "Admin"

At this point, I can no longer install the AWS integration from the Default space.

**Workaround**

After some testing, I noticed I could install the AWS integration again by creating a new space.

- Create a new space called "Another One" and switch to it
- Install the AWS integration

I am still unable to install integrations from the Default space, but at least I can do it from another one (no pun intended) ad start ingesting data.

This can help to wait for a proper fix, coming in 8.6.

**Comment by zmoog** [comment]
This is the DevTools-friendly version of the [comment above](https://github.com/elastic/integrations/issues/4895#issuecomment-1363874035).

```shell
#
# Create a super user that can change privileged data
#

POST _security/role/fleet_superuser
{
  "indices": [
    {
      "names": [
        ".fleet*",
        ".kibana*"
      ],
      "privileges": [
        "all"
      ],
      "allow_restricted_indices": true
    }
  ]
}

POST _security/user/fleet_superuser
{
  "password": "secretstuff",
  "roles": [
    "superuser",
    "fleet_superuser"
  ]
}


#
# Delete by query
#

POST /.kibana/_delete_by_query
{
  "query": {
    "bool": {
      "filter": [
        {
          "terms": {
            "type": [
              "dashboard",
              "visualization",
              "map",
              "lens",
              "search"
            ]
          }
        }
      ],
      "minimum_should_match" : 1,
      "should": [
        {
          "prefix": {
            "id": {
              "value": "aws-"
            }
          }
        },
        {
          "prefix": {
            "originId": {
              "value": "aws-"
            }
          }
        }
      ]
    }
  }
}

# result

{
  "took": 147,
  "timed_out": false,
  "total": 44,
  "deleted": 44,
  "batches": 1,
  "version_conflicts": 0,
  "noops": 0,
  "retries": {
    "bulk": 0,
    "search": 0
  },
  "throttled_millis": 0,
  "requests_per_second": -1,
  "throttled_until_millis": 0,
  "failures": []
}
```

**Comment by zmoog** [comment]
It looks like Julia put together a cleanup process that works.

## Overview

1. Create the `fleet_superuser` user 
2. Run the clean-up
3. Delete the `fleet_superuser` user 

## 1. Create the `fleet_superuser` user 

Open the **Dev Tools** and run the following requests:

```shell
POST _security/role/fleet_superuser
{
  "indices": [
    {
      "names": [
        ".fleet*",
        ".kibana*"
      ],
      "privileges": [
        "all"
      ],
      "allow_restricted_indices": true
    }
  ]
}

POST _security/user/fleet_superuser
{
  "password": "<PUT A PASSWORD HERE>",
  "roles": [
    "superuser",
    "fleet_superuser"
  ]
}
```

Replace `<PUT A PASSWORD HERE>` with something unique to this environment.

## 2. Run the clean-up

Open a terminal, and run the following requests using `curl`.

```shell
export ES_USERNAME="fleet_superuser"
export ES_PASSWORD="<PUT A PASSWORD HERE>"
export ES_HOST="https:// .... .elastic-cloud.com:443"

curl -sk -XPOST --user ${ES_USERNAME}:${ES_PASSWORD} -H 'content-type:application/json' \
-H'x-elastic-product-origin:fleet' \
${ES_HOST}/.kibana/_delete_by_query -d '
{
  "query": {
    "bool": {
      "filter": [
      {
        "terms": {
          "type": [
            "dashboard",
            "visualization",
            "map",
            "lens",
            "search"
          ]
        }
      }
    ],
      "must": [
        {"simple_query_string": {
          "query": "\"aws-*\""
        }}
      ]
    }
  }
}'

curl -sk -XPOST --user ${ES_USERNAME}:${ES_PASSWORD} -H 'content-type:application/json' \
-H'x-elastic-product-origin:fleet' \
${ES_HOST}/.kibana/_delete_by_query -d '
{
  "query": {
    "bool": {
      "filter": [
        {
          "terms": {
            "type": [
              "dashboard",
              "visualization",
              "map",
              "lens",
              "search"
            ]
          }
        }
      ],
      "minimum_should_match" : 1,
      "should": [
        {
          "prefix": {
            "id": {
              "value": "aws-"
            }
          }
        },
        {
          "prefix": {
            "originId": {
              "value": "aws-"
            }
          }
        }
      ]
    }
  }
}'

curl -sk -XDELETE --user ${ES_USERNAME}:${ES_PASSWORD} -H 'content-type:application/json' \
-H'x-elastic-product-origin:fleet' \
${ES_HOST}/.kibana/_doc/search:aws-395fef40-5a52-11ed-a807-bd2da8f2e79b

curl -sk -XDELETE --user ${ES_USERNAME}:${ES_PASSWORD} -H 'content-type:application/json' \
-H'x-elastic-product-origin:fleet' \
${ES_HOST}/.kibana/_doc/search:aws-839e3db0-5a51-11ed-a807-bd2da8f2e79b

curl -sk -XDELETE --user ${ES_USERNAME}:${ES_PASSWORD} -H 'content-type:application/json' \
-H'x-elastic-product-origin:fleet' \
${ES_HOST}/.kibana/_doc/search:aws-dffd2200-5a52-11ed-a807-bd2da8f2e79b
```

Now you can try to install the AWS integration again.


## 3. Delete the `fleet_superuser` user 

We no longer need this user, and we must throw it away.

You can go back to the **Dev Tools** and run the following requests:

```shell
DELETE _security/user/fleet_superuser 

DELETE _security/role/fleet_superuser 
```

**Comment by zmoog** [comment]
After this cleanup, I was able to install the AWS integration on my test 8.5.3 cluster.
